[package]
name = "gh-difftool"
version = "0.1.14"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive", "env"] }
displaydoc = "0.2.3"
futures = { version = "0.3.25", default_features = false }
gix-config = "0.19.0"
itertools = "0.10.5"
once_cell = "1.16.0"
parse_link_header = "0.3.3"
reqwest = { version = "0.11.12", features = ["blocking", "native-tls-vendored"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tempfile = "3.3.0"
tokio = { version = "1.22.0", features = ["full"] }
url = "2.3.1"
which = "4.3.0"

[dev-dependencies]
assert_cmd = "2.0.6"
httpmock = "0.6.6"
mockall = "0.11.2"
temp_testdir = "0.2.3"
textwrap = "0.16.0"
yare = "1.0.2"


# Need to give credit to https://github.com/johnthagen/min-sized-rust for these
# options to help reduce the binary size. Knocked off about 66% of the size with
# these options
[profile.release]
opt-level = 'z'     
lto = true          
codegen-units = 1   
panic = 'abort'     
strip = true        
