[package]
name = "gh-difftool"
version = "0.1.5"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive", "env"] }
futures = { version = "0.3.25", default_features = false }
reqwest = { version = "0.11.12", features = ["blocking", "native-tls-vendored"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tempfile = "3.3.0"
tokio = { version = "1.22.0", features = ["full"] }

[dev-dependencies]
assert_cmd = "2.0.6"
httpmock = "0.6.6"
mockall = "0.11.2"
temp_testdir = "0.2.3"
textwrap = "0.16.0"
