[package]
name = "gh-difftool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["derive", "env"] }
patch = "0.6.0"
tempfile = "3.3.0"

[dev-dependencies]
mockall = "0.11.2"
temp_testdir = "0.2.3"
textwrap = "0.16.0"

# Pull in https://github.com/uniphil/patch-rs/pull/16 to fix https://github.com/uniphil/patch-rs/pull/15
[patch.crates-io]
patch = { git = "https://github.com/wfraser/patch-rs.git", branch = "hunk-header-context" }
