[package]
name = "gh-difftool"
version = "0.1.4"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive", "env"] }
reqwest = { version = "0.11.12", features = ["blocking", "native-tls-vendored"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tempfile = "3.3.0"

[dev-dependencies]
httpmock = "0.6.6"
mockall = "0.11.2"
temp_testdir = "0.2.3"
textwrap = "0.16.0"
