[package]
name = "gh-difftool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall_double = "0.3.0"

[dev-dependencies]
assert_cmd = "2.0.4"
mockall = { version = "0.11.2", features = ["nightly"] }
