name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: android-arm64
            os: ubuntu-latest
            cargo_build_target: aarch64-linux-android
          - target: darwin-amd64
            os: macos-latest
            cargo_build_target: x86_64-apple-darwin
          - target: darwin-arm64
            os: macos-latest
            cargo_build_target: aarch64-apple-darwin
          - target: linux-amd64
            os: ubuntu-latest
            cargo_build_target: x86_64-unknown-linux-gnu
          - target: windows-amd64
            os: windows-latest
            cargo_build_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    env:
      CARGO_BUILD_TARGET: ${{ matrix.cargo_build_target }}
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v1
        with: 
          build_script_override: "scripts/build_dist.sh"
